language: node_js
node_js:
  - 10

branches:
  only:
    - master

before_script:
  - yarn install

script:
  - yarn build

notifications:
  email: false
  slack:
    rooms:
      - glriaroom:GJpK4bqmhqF9CtV1l4qVSp6Q#devops
    on_success: change # default : always
    on_failure: always # default : always
